NAME: prova-container
GENUS: ''
SPECIES: ''
TYPE: fasta
PAIRED: 'yes'
INPUT: /home/adriana/bacExplorer_tests/Core_tree_2
IDENTITY: 90
COVERAGE: 90
THREADS_NUMBER: 2
GENOMAD_ANALYSIS: 'no'
SNIPPY: 'no'
PHYLO_TREE: 'yes'
REFERENCE_GENOME: "/home/adriana/bacExplorer_tests/Genomi/OG1RF.fa"
VBCG: 'no'