import os
import subprocess
import json
import glob
import shutil
import psutil
import pandas as pd

configfile: "config.yaml"

shell.executable("/usr/bin/bash")

conda_info = subprocess.run(['conda', 'info', '--json'], capture_output=True, text=True)
info = json.loads(conda_info.stdout)

type = config["TYPE"]
THREADS_NUMBER = config["THREADS_NUMBER"]
IDENTITY = config["IDENTITY"]
COVERAGE = config["COVERAGE"]
ANALYSIS_NAME = config["NAME"]
GENUS = config["GENUS"]
SPECIES = config["SPECIES"]
paired = config["PAIRED"]
GENOMAD_ANALYSIS = config["GENOMAD_ANALYSIS"]

# PATH_PROJECT is the input folder provided by the user
PATH_ENV = os.path.join(info["envs_dirs"][0], "bacEnv")
PATH_PROJECT = config["INPUT"]
PATH_OUTPUT = os.path.join(PATH_PROJECT, "output")
PATH_SCRIPT = workflow.basedir
PATH_TOOLS = "/project/tools"
PATH_VIRULENCE_DB = os.path.join(PATH_SCRIPT, "resources/virulencefinder_db/")
PATH_KRAKEN_DB = os.path.join(PATH_SCRIPT, "resources/kraken2db")
PATH_GENOMAD = os.path.join(PATH_SCRIPT, "resources/genomad_db")

SAMPLES = []
FASTQ_SAMPLES = []

print(f"PATH_SCRIPT: {PATH_SCRIPT}")
print(f"PATH_PROJECT: {PATH_PROJECT}")
print(f"PATH_OUTPUT: {PATH_OUTPUT}")
print(f"PATH_ENV: {PATH_ENV}")
print(f"PATH_TOOLS: {PATH_TOOLS}")
print(f"GENOMAD_ANALYSIS: {GENOMAD_ANALYSIS}")

# create directories in the output folder
DIRS_LIST = ["abricate", "abricate_ecoli", "agrvate", "amrfinder", "ectyper", "emmtyper", "genomad", "hicap", "kleborate",
"kleborate_escherichia", "kraken2", "legsta", "lissero", "mlst", "pbptyper", "shigatyper", "spatyper", "sccmec", "fimtyper",
"virulencefinder", "shigeifinder", "ngmaster", "ClermonTyping", "pasty", "meningotype", "quality_assessment"]

if not os.path.exists(PATH_PROJECT):
    raise ValueError(f"Path {PATH_PROJECT} does not exist!")

os.makedirs(PATH_OUTPUT, exist_ok=True)
os.chmod(PATH_OUTPUT, 0o777)

for d in DIRS_LIST:
    os.makedirs(os.path.join(PATH_OUTPUT, d), exist_ok=True)
    done_file = os.path.join(PATH_OUTPUT, d, '.done')
    with open(done_file, 'w') as f:
        f.write("Done\n")

# create "trim" folder only for fastq analyses
if type == "fastq":
    os.makedirs(os.path.join(PATH_OUTPUT, "trim"), exist_ok=True)
    done_file = os.path.join(PATH_OUTPUT, d, '.done')
    with open(done_file, 'w') as f:
        f.write("Done\n")

include: "pre_processing.smk"

if type == "fastq":
    os.makedirs(os.path.join(PATH_PROJECT, "fastq"), exist_ok=True)
    include: "fastq_analysis.smk"
    include: "fasta_analysis.smk"
    include: "quality_assessment.smk"
elif type == "fasta":
    include: "fasta_analysis.smk"
    include: "quality_assessment.smk"
else:
    raise ValueError(f"Type: {type} not supported")

fasta_checkpoint = os.path.join(PATH_OUTPUT, "fasta_analysis_checkpoint.txt")