import React from "react";
// import htmlFile from '../../../../snakemake/Report.html'

// gerarchia richiesta dal tool:
// - analysis_directory
// - - analysis1
// - - - samples
// - - - - sample1.fasta
// - - - - sample2.fasta
// - - - - ...
// - - - - output
// - - - - - abricate
// - - - - - AMRfinder
// - - - - - ...
// - - - - - file (generated by report.Rmd)
// - - - - - analysis1_report.html
// - - analysis2
// - - ...

//seleziona la directory delle prove e restituisci l'html del report 

export default function Report(){
    // return <div dangerouslySetInnerHTML={{ __html: htmlFile }} />;
    return <></>
}